### ISSUE TITLE
They can't create a custom name

### ISSUE THREAD

**Issue by MyAlien** [hatienl0i261299/Soundcloud#1]
Hello,
They can't create a custom name
Can you solve the problem please?

Use command line : 
`soundcloud.py -s outputfilename.mp3 -u https://soundcloud.com/kauprod/546-kauprod-un-voyage-dans`

`soundcloud.py -s outputfilename -u https://soundcloud.com/kauprod/546-kauprod-un-voyage-dans`

`soundcloud.py -s outputfilename.mp3 -u https://soundcloud.com/kauprod/546-kauprod-un-voyage-dans
[*] : Extracting client id
[*] : Extracting info of track . (done)
Traceback (most recent call last):
  File "soundcloud.py", line 383, in <module>
    main(sys.argv)
  File "soundcloud.py", line 373, in main
    extract.run()
  File "soundcloud.py", line 25, in run
    return self._real_extract()
  File "soundcloud.py", line 61, in _real_extract
    return self._download_track(dict_info_track=dict_info_track, _show_all_info=self._show_all_info)
  File "soundcloud.py", line 187, in _download_track
    os.mkdir(path_save)
FileNotFoundError: [Errno 2] No such file or directory: 'dsfdsf.mp3/DOWNLOAD'`

Thank you for your answer.

**Comment by hatienl0i2612** [comment]
Hi
if only one track, you can rename after downloaded
